### ISSUE TITLE
Crash issue when lauching the exe

### ISSUE THREAD

**Issue by ThibaudGUE** [Dooque/aoe2-de-in-game-rating-overlay#1] opened 2021-08-22 14:13 UTC
Hey,

Thanks for your work first, i'm trying to use your tool but when i launch it IG i got an error box with : Failed to execute script "aoe2de-in-game-rating-overlay"

**Comment by jboehler** [comment] 2021-09-10 05:10
Hello

First also thanks for sharing your Work!

I also get the same Error Message :-/ 

also hard to debug what the issue is

![image](https://user-images.githubusercontent.com/1150699/132802794-c45ad4b2-d564-4ddb-b692-8d98a32412b9.png)

**Comment by ThibaudGUE** [comment] 2021-09-11 10:49
Hello @jboehler 
A friend fixed it, you can download the exe file there : https://we.tl/t-usGy8OjBMC
I join a screenn to show you the result, TG [ELO] [WINRATE] [NB GAMES] and same for 1v1. sometimes you'll see warning to tell you if opponents are matchmaking abuser or smurfs ;)
Enjoy

![unknown](https://user-images.githubusercontent.com/89347101/132945423-761997ab-8a9b-4bae-bf8c-33f041bb1fab.png)

**Comment by jboehler** [comment] 2021-09-11 19:21
@ThibaudGUE thx for sharing 

how the WARNING abuser or smurf Works?

**Comment by ThibaudGUE** [comment] 2021-09-12 10:30
Hello,

My friend sent me the .py file. The conf file is just the file that contains your ID + some limits that leads to smurf warnings but i've written raw code in my example, you can uncomment these lines to get the older version : 
NOMBRE_GAMES_MIN = 10 # int(configuration_file_lines[1])
ELO_SOLO_MAX = 1500 # int(configuration_file_lines[2])
ELO_TG_MAX = 2500 # int(configuration_file_lines[3])
WIN_RATE_MAX = 65# int(configuration_file_lines[4])

Here is the files : 
https://we.tl/t-0tOgFLRmLQ

and for the version that you have DL everything is in your "RATING_OVERLAY_CONF.txt" file, you can switch the first lines according to your ID, min games from which you consider the opponent is a smurf, max elo from which you consider he is abusing matchmaking (usefull in TG) and same for winrate (60)

1628909
75
1500
60
----------------------------------------------------------
Profil_ID
Min_games
Max_elo_SOLO
Max_Winrate

**Comment by Aoe2Overlay** [comment] 2021-09-24 05:45
@ThibaudGUE in the end i wrote my own overlay with C# and published it on github. I have also made it more configurable.
https://github.com/kickass-panda/Aoe2DEOverlay

**Comment by ThibaudGUE** [comment] 2021-09-24 16:02
Yo,

that why you didn't answer quickly :p
You could have done the same from the initial project imo
But great work anyway

Regards,

Thibaud

**Comment by Dooque** [comment] 2021-10-08 18:05
Hi guys, thanks for the feedback. This is still in beta mode. I'm working on a new version where I'll fix all those error and will add new features.

**Comment by Dooque** [comment] 2021-10-08 18:23
@ThibaudGUE tell your friend if he wants to contribute everyone is welcome, also you can fork and send the pull-request. The more people we can get into this the more powerful and stable app we can get. This is for everyone so everyone is welcome to participate.

**Comment by Dooque** [comment] 2021-10-08 18:26
Just to let you know, whichever the version you're using there are problems after every Microsoft server maintenance, I'm working on that as well, at least don't let the app crash when servers don't retrieve information.

Again, thanks for using it, thanks for the feedback, and stay tune, new release coming soon (you can check the develop branch).

Regards.

**Comment by ThibaudGUE** [comment] 2021-10-09 11:41
Hey,

My friend just did a quick fix to use it but I don't think he wants to participate to the dev.
Great job and keep going 👍 

regards,

Thibaud

**Comment by Dooque** [comment] 2021-10-09 14:45
Fixed in the lastest release [v1.0.0](https://github.com/Dooque/aoe2-de-in-game-rating-overlay/archive/refs/tags/v1.0.0.zip)

**Closed as completed by Dooque** 2021-10-09 14:45 UTC
